In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [5]:
dataset=pd.read_csv("Social_Network_Ads.csv")

In [7]:
dataset

      User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]

In [9]:
dataset=pd.get_dummies(dataset,dtype=int,drop_first=True)

In [11]:
dataset

      User ID  Age  EstimatedSalary  Purchased  Gender_Male
0    15624510   19            19000          0            1
1    15810944   35            20000          0            1
2    15668575   26            43000          0            0
3    15603246   27            57000          0            0
4    15804002   19            76000          0            1
..        ...  ...              ...        ...          ...
395  15691863   46            41000          1            0
396  15706071   51            23000          1            1
397  15654296   50            20000          1            0
398  15755018   36            33000          0            1
399  15594041   49            36000          1            0

[400 rows x 5 columns]

In [13]:
dataset=dataset.drop("User ID",axis=1)

In [15]:
dataset

     Age  EstimatedSalary  Purchased  Gender_Male
0     19            19000          0            1
1     35            20000          0            1
2     26            43000          0            0
3     27            57000          0            0
4     19            76000          0            1
..   ...              ...        ...          ...
395   46            41000          1            0
396   51            23000          1            1
397   50            20000          1            0
398   36            33000          0            1
399   49            36000          1            0

[400 rows x 4 columns]

In [17]:
dataset["Purchased"].value_counts()

Purchased
0    257
1    143
Name: count, dtype: int64

In [19]:
dataset.columns

Index(['Age', 'EstimatedSalary', 'Purchased', 'Gender_Male'], dtype='object')

In [23]:
independent=dataset[['Age', 'EstimatedSalary','Gender_Male']]

In [25]:
independent

     Age  EstimatedSalary  Gender_Male
0     19            19000            1
1     35            20000            1
2     26            43000            0
3     27            57000            0
4     19            76000            1
..   ...              ...          ...
395   46            41000            0
396   51            23000            1
397   50            20000            0
398   36            33000            1
399   49            36000            0

[400 rows x 3 columns]

In [27]:
dependent=dataset[['Purchased']]

In [29]:
dependent

     Purchased
0            0
1            0
2            0
3            0
4            0
..         ...
395          1
396          1
397          1
398          0
399          1

[400 rows x 1 columns]

In [31]:
independent.shape

(400, 3)

In [33]:
dependent.shape

(400, 1)

In [37]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(independent,dependent,test_size=0.30,random_state=0)

In [49]:
from sklearn.neighbors import KNeighborsClassifier
classifier=KNeighborsClassifier(n_neighbors=7,metric='minkowski',p=2)
classifier.fit(x_train,y_train)

C:\Anaconda3\Lib\site-packages\sklearn\neighbors\_classification.py:239: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)

KNeighborsClassifier(n_neighbors=7)

In [51]:
y_pred=classifier.predict(x_test)

In [55]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,y_pred)

In [57]:
print(cm)

[[72  7]
 [13 28]]

In [59]:
from sklearn.metrics import classification_report
clf_report=classification_report(y_test,y_pred)

In [61]:
print(clf_report)

              precision    recall  f1-score   support

           0       0.85      0.91      0.88        79
           1       0.80      0.68      0.74        41

    accuracy                           0.83       120
   macro avg       0.82      0.80      0.81       120
weighted avg       0.83      0.83      0.83       120

In [63]:
import pickle

In [65]:
filename="finalaized_model_KNN.sav"

In [67]:
pickle.dump(classifier,open(filename,'wb'))

In [71]:
loaded_model=pickle.load(open("finalaized_model_KNN.sav",'rb'))

In [77]:
result=loaded_model.predict([[243,400,1]])

C:\Anaconda3\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  warnings.warn(

In [79]:
result

array([0], dtype=int64)